#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#
# http://marius.scurtescu.com/?p=102
# http://gnomefiles.org/app.php?soft_id=1059

LOGFILE=`mktemp -t git_log.XXXXXX`

git log "$@" > $LOGFILE
zenity --text-info --title="Git: Log" --filename=$LOGFILE --width=600 --height=400 --window-icon="`dirname $0`/git.xpm"
rm -f $LOGFILE
