#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#
# http://marius.scurtescu.com/?p=102
# http://gnomefiles.org/app.php?soft_id=1059

LOGFILE=`mktemp -t git_blame.XXXXXX`

git blame "$@" > $LOGFILE
zenity --text-info --title="Git: Blame" --filename=$LOGFILE --width=600 --height=400 --window-icon="`dirname $0`/git.png"
rm -f $LOGFILE
