#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#
# http://marius.scurtescu.com/?p=102
# http://gnomefiles.org/app.php?soft_id=1059

LOGFILE=`mktemp -t git_checkout.XXXXXX`
ICONPATH="`dirname $0`/git.png"

target=`zenity --entry --title="Git: Checkout" --text="Enter object to checkout" --width=400 --window-icon="$ICONPATH" 2>&1`

if [ $? -eq 0 ] ; then
    git checkout $target &> $LOGFILE
    zenity --text-info --title="Git: Checkout" --filename=$LOGFILE --width=600 --height=400 --window-icon="$ICONPATH"
    rm -f $LOGFILE
fi
