#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#
# http://marius.scurtescu.com/?p=102
# http://gnomefiles.org/app.php?soft_id=1059

LOGFILE=`mktemp -t git_clone.XXXXXX`
ICONPATH="`dirname $0`/git.xpm"

URL=`zenity --entry --title="Git: Clone" --text="Enter repository URL:" --entry-text="git://" --width=400 --window-icon="$ICONPATH" 2>&1`

if [ $? -eq 0 ] ; then
    git checkout $URL &> $LOGFILE
    zenity --text-info --title="Git: Clone" --filename=$LOGFILE --width=600 --height=400 --window-icon="$ICONPATH"
    rm -f $LOGFILE
fi
