#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#

if [ -r "`dirname "$0"`/git.conf" ]; then
  . "`dirname "$0"`/git.conf"
elif [ -r "`dirname "$0"`/../git.conf" ]; then
  . "`dirname "$0"`/../git.conf"
else
  exit 1
fi

if [ -z "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" ]; then
  $GIT $GIT_OPTS revert . 1>> "$OUTPUT" 2>> "$OUTPUT"
  _zenity_info "$?" "Unknown" "Unknown error (more information can be found at ~/.xsession-errors)"
else
  $GIT $GIT_OPTS revert "$@" 1>> "$OUTPUT" 2>> "$OUTPUT"
  _zenity_info "$?" "Unknown" "Unknown error (more information can be found at ~/.xsession-errors)"
fi

